# TREC 2018 Precision Medicine

In [1]:
import json
from json2html import *
from IPython.display import HTML
import pandas

import os, sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)
from trec_utils import utils, evaluation

Load and show configuration

In [2]:
config = utils.load_config()

In [3]:
topics_all = evaluation.get_topics('./topics/topics2017.xml')
qrels_all = evaluation.get_qrels('./gold-standard/abstracts.2017.qrels')
TOPIC = 2

In [4]:
topic = topics_all[(topics_all.topic==TOPIC)]
qrels = evaluation.qrels_of_topics(qrels_all, topic)
topic

,topic,disease,gene,gene1,gene2,gene3,sex,age
2,2,Colon cancer,"KRAS (G13D), BRAF (V600E)",KRAS (G13D),BRAF (V600E),,male,52

In [6]:
run, params = evaluation.run(topic)
params['query_template'] = 'topic-optimized.json'
results, aggregated = evaluation.evaluate(qrels[(qrels.relev.isin([2]))], run)
run, params = evaluation.run(topic, params)
aggregated

RUN: FIXME TOPICS: 1 {'disease_tie_breaker': 0.5, 'gene_tie_breaker': 0.5, 'query_template': 'baseline.json', 'disease_boost': 1.5, 'gene_boost': 1}
RUN: FIXME TOPICS: 1 {'disease_tie_breaker': 0.5, 'gene_tie_breaker': 0.5, 'query_template': 'topic-optimized.json', 'disease_boost': 1.5, 'gene_boost': 1}

{'P_10': 0.9, 'Rprec': 0.4231, 'ndcg': 0.7551, 'recall_1000': 0.8205}

In [7]:
run, params = evaluation.run(topic)
params['query_template'] = 'topic-optimized2.json'
results, aggregated = evaluation.evaluate(qrels[(qrels.relev.isin([2]))], run)
run, params = evaluation.run(topic, params)
aggregated

RUN: FIXME TOPICS: 1 {'disease_tie_breaker': 0.5, 'gene_tie_breaker': 0.5, 'query_template': 'topic-optimized.json', 'disease_boost': 1.5, 'gene_boost': 1}
RUN: FIXME TOPICS: 1 {'disease_tie_breaker': 0.5, 'gene_tie_breaker': 0.5, 'query_template': 'topic-optimized2.json', 'disease_boost': 1.5, 'gene_boost': 1}

{'P_10': 0.9, 'Rprec': 0.4231, 'ndcg': 0.7231, 'recall_1000': 0.7692}

Check relevant documents missed and why (for topic 2 for example)

In [8]:
run_set = set(run[(run.TOPIC_NO==TOPIC)].ID)
qrels_set = set(qrels[(qrels.relev.isin([2]))].doc_id)
qrels_set.difference(run_set)

{'15735008',
 '16448675',
 '17293392',
 '17517901',
 '18097554',
 '18098337',
 '19959686',
 '21457162',
 '21681432',
 '22210186',
 '22972628',
 '23071293',
 '23112547',
 '23446022',
 '23462926',
 '23763264',
 '24025253',
 '24244575',
 '24522186',
 '24805134',
 '25073438',
 '25386108',
 '25469291',
 '25696788',
 '26359417',
 '26371285',
 '26623049',
 '27099668',
 'AACR_2014-2009',
 'AACR_2017-3066',
 'AACR_2017-4639',
 'AACR_2017-5162',
 'ASCO_32653-65'}

In [9]:
qrels

       topic           doc_id  relev
21951      2         25527633      2
21956      2         20162668      2
21963      2         19087308      2
21977      2         25073438      2
21983      2         24861115      2
21992      2         23015072      2
21994      2         27099668      2
21998      2         24104864      2
22011      2         18098337      2
22012      2         23462926      2
22014      2         27770401      2
22016      2         22210186      2
22019      2   AACR_2013-1219      2
22024      2         20962618      2
22027      2  ASCO_116614-132      2
22029      2         19669908      2
22031      2         18676857      2
22032      2   ASCO_60628-101      2
22035      2         17293392      2
22044      2         25696791      2
22054      2         25599653      2
22058      2         24778007      2
22059      2   AACR_2017-5162      2
22062      2         23849768      2
22063      2         27354468      2
22065      2         27569082      2
22074      2         27001432      2
22075      2   AACR_2014-2009      2
22077      2         26861657      2
22083      2         26371285      2
...      ...              ...    ...
22582      2         12432918      0
22583      2         22549374      0
22584      2         10720084      0
22588      2  ASCO_111305-132      0
22590      2         21816436      0
22594      2   AACR_2013-2782      0
22596      2         16524974      0
22597      2         26364606      0
22599      2          6369971      0
22600      2         23190154      0
22601      2         22934546      0
22602      2         26190239      0
22604      2         15764920      0
22605      2         26513490      0
22606      2         19434531      0
22607      2         18279056      0
22608      2         18488072      0
22609      2         10950460      0
22612      2         16866638      0
22615      2          9750478      0
22619      2         10648274      0
22621      2         22951975      0
22624      2         23274581      0
22625      2         25704541      0
22627      2         24429895      0
22632      2         21289876      0
22636      2         17574431      0
22637      2         24139215      0
22639      2         25937573      0
22641      2         11429486      0

[691 rows x 3 columns]