# TREC 2018 Precision Medicine

In [1]:
import json
from json2html import *
from IPython.display import HTML
import eval
import pandas

Load and show configuration

In [2]:
with open('config.json', 'r') as f:
    config = json.load(f)
#HTML(json2html.convert(json = config))

In [3]:
topics_all = eval.get_topics('./topics/topics2017.xml')
qrels_all = eval.get_qrels('./gold-standard/abstracts.2017.qrels')
TOPIC = 2

In [4]:
topic = topics_all[(topics_all.topic==TOPIC)]
qrels = eval.qrels_of_topics(qrels_all, topic)
topic

,topic,disease,gene,gene1,gene2,gene3,sex,age
2,2,Colon cancer,"KRAS (G13D), BRAF (V600E)",KRAS (G13D),BRAF (V600E),,male,52

In [5]:
run, params = eval.run(topic)
params['query_template'] = 'topic-optimized.json'
run, params = eval.run(topic, params)

RUN: FIXME TOPICS: 1 {'disease_boost': 1.5, 'query_template': 'baseline.json', 'disease_tie_breaker': 0.5, 'gene_tie_breaker': 0.5, 'gene_boost': 1}
RUN: FIXME TOPICS: 1 {'disease_boost': 1.5, 'query_template': 'topic-optimized.json', 'disease_tie_breaker': 0.5, 'gene_tie_breaker': 0.5, 'gene_boost': 1}

In [6]:
results, aggregated = eval.evaluate(qrels[(qrels.relev.isin([2]))], run)

In [7]:
aggregated

{'P_10': 0.9, 'Rprec': 0.2949, 'ndcg': 0.4416, 'recall_1000': 0.3782}

Check relevant documents missed and why (for topic 2 for example)

In [8]:
run_set = set(run[(run.TOPIC_NO==TOPIC)].ID)
qrels_set = set(qrels[(qrels.relev.isin([2]))].doc_id)
qrels_set.difference(run_set)

{'17440063',
 '18098337',
 '18199160',
 '19001320',
 '19087308',
 '19474002',
 '19913317',
 '20162668',
 '20177422',
 '20616366',
 '20635392',
 '20645028',
 '20962618',
 '21424126',
 '21455633',
 '21457162',
 '21681432',
 '22043994',
 '22180495',
 '22210186',
 '22314188',
 '22899370',
 '22933967',
 '22972628',
 '23015072',
 '23033302',
 '23071293',
 '23112547',
 '23157823',
 '23375249',
 '23462926',
 '23537520',
 '23650027',
 '23666916',
 '23763264',
 '23773459',
 '23849768',
 '23938455',
 '24104864',
 '24166180',
 '24244575',
 '24352906',
 '24522186',
 '24522420',
 '24523613',
 '24642870',
 '24778007',
 '24798160',
 '24832158',
 '24833563',
 '24861115',
 '25073438',
 '25469291',
 '25527633',
 '25550768',
 '25696788',
 '25862899',
 '25924923',
 '25956750',
 '25983749',
 '26184520',
 '26187617',
 '26359417',
 '26371285',
 '26623049',
 '26664139',
 '26812186',
 '26861657',
 '26884114',
 '27001432',
 '27036313',
 '27099668',
 '27114605',
 '27246726',
 '27308494',
 '27341594',
 '27354468',
 '27438990',
 '27540971',
 '27569082',
 '27672042',
 'AACR_2012-4510',
 'AACR_2013-1219',
 'AACR_2014-4418',
 'AACR_2017-4639',
 'AACR_2017-5162',
 'AACR_2017-748',
 'ASCO_132217-144',
 'ASCO_145142-156',
 'ASCO_160325-173',
 'ASCO_191724-199',
 'ASCO_34187-65',
 'ASCO_34230-65',
 'ASCO_50132-74',
 'ASCO_60628-101',
 'ASCO_98608-114',
 'ASCO_99452-114'}

In [9]:
qrels

      topic           doc_id  relev
4828      2         25924923      2
4830      2         19474002      2
4833      2         19913317      2
4834      2   AACR_2017-5162      2
4835      2         24522420      2
4836      2  ASCO_126870-144      2
4838      2         27540971      2
4840      2  ASCO_191724-199      2
4845      2    ASCO_34230-65      2
4863      2   AACR_2014-2009      2
4865      2         25696788      2
4868      2         17517901      2
4869      2   ASCO_60628-101      2
4870      2         24832158      2
4871      2         24025253      2
4873      2         15735008      2
4879      2         24019539      2
4892      2         25899003      2
4894      2         23015072      2
4896      2         26376292      2
4902      2         22210186      2
4904      2         23572025      2
4907      2         25936694      2
4909      2         26623049      2
4911      2   AACR_2013-1219      2
4913      2         27048246      2
4916      2         19001320      2
4917      2         24861115      2
4926      2         22972628      2
4928      2         22899370      2
...     ...              ...    ...
5456      2         25789707      0
5458      2         16230380      0
5459      2         12134620      0
5460      2         18488072      0
5464      2         22934546      0
5465      2         11904375      0
5466      2          2824139      0
5467      2         16239255      0
5469      2         18628249      0
5473      2         15075001      0
5475      2         26508523      0
5478      2         19343149      0
5479      2          2253831      0
5480      2          6092920      0
5481      2         19551857      0
5482      2         19584382      0
5485      2         22531017      0
5486      2         16256179      0
5487      2          2927393      0
5489      2         26667174      0
5493      2         15771788      0
5494      2         26190239      0
5496      2         26005530      0
5498      2  ASCO_167501-176      0
5501      2         25602793      0
5502      2         24429895      0
5503      2         25794709      0
5506      2         11307309      0
5507      2         25332244      0
5508      2         27350555      0

[691 rows x 3 columns]